[[plugins]]
repo = "ellisonleao/gruvbox.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("gruvbox").setup({
  contrast = "soft",
  transparent_mode = true,
  palette_overrides = {
    bright_green = "#98971a",
  },
})
"""

# [[plugins]]
# repo = "catppuccin/nvim"
# on_event = ['BufRead', 'CursorHold']
# lua_source = """
# require("catppuccin").setup({})
# vim.cmd.colorscheme "catppuccin"
# """

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'CursorHold']
lua_source = """
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  ensure_installed = 'all'
}
"""

[[plugins]]
repo = "numToStr/Comment.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('Comment').setup()
"""

[[plugins]]
repo = "shortcuts/no-neck-pain.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('no-neck-pain').setup()
"""

[[plugins]]
repo = "Shougo/deol.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = '''
require("hooks/deol")
'''

[[plugins]]
repo = "vim-jp/vimdoc-ja"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = "machakann/vim-sandwich"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = ['sg.nvim']

[[plugins]]
repo = "simeji/winresizer"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = "folke/noice.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("noice").setup({
  views = {
    cmdline_popup = {
      position = {
        row = "5%",
        col = "50%",
      },
      size = {
        width = "60%",
        height = "auto",
      },
      border = {
        style = "rounded",
        padding = { 0, 1 },
      },
    },
  },
})
"""

[[plugins]]
repo = "MunifTanjim/nui.nvim"
on_source = ['noice.nvim']

[[plugins]]
repo = "rcarriga/nvim-notify"
on_source = ['noice.nvim']
lua_source = """
require("notify").setup({
  background_colour = "#000000",
  timeout = 2000,
})
"""

[[plugins]]
repo = "hrsh7th/nvim-insx"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("hooks/insx")
"""

[[plugins]]
repo = "lambdalisue/vim-gin"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = "sourcegraph/sg.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('sg').setup({
})
"""

[[plugins]]
repo = "github/copilot.vim"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = 'dense-analysis/ale'
on_event = ['BufRead', 'CursorHold']
hook_add = '''
let g:ale_fixers = {
\   'typescript': ['prettier'],
\   'typescriptreact': ['prettier'],
\   'javascript': ['prettier'],
\   'javascriptreact': ['prettier'],
\   'css': ['prettier'],
\}

let g:ale_sign_error = 'P>'
let g:ale_sign_warning = 'P-'
let g:ale_echo_msg_format = '[%linter%] %code: %%s'
let g:ale_statusline_format = ['E%d', 'W%d', 'OK']

nmap <silent> <C-w>j <Plug>(ale_next_wrap)
nmap <silent> <C-w>k <Plug>(ale_previous_wrap)

let g:ale_fix_on_save = 1
let g:ale_javascript_prettier_use_local_config = 1
let g:ale_javascript_prettier_options = '--single-quote --trailing-comma all'
'''
